import React from "react";
import { Sparkles } from "lucide-react";

export const AnalysisSummaryCard = ({ summary }) => {
  return (
    <div className="bg-[#0d1b36] border border-slate-800 rounded-2xl p-6">

      <div className="flex items-center gap-3 mb-5">

        <div className="w-11 h-11 rounded-xl bg-indigo-600 flex justify-center items-center">
          <Sparkles size={20} />
        </div>

        <div>
          <h2 className="text-xl font-semibold">
            AI Summary
          </h2>

          <p className="text-slate-400 text-sm">
            Overall evaluation generated by AI
          </p>
        </div>

      </div>

      <div className="rounded-xl bg-[#07162d] border border-slate-700 p-5">

        <p className="text-slate-300 leading-8">
          {summary}
        </p>

      </div>

    </div>
  );
};